### ISSUE TITLE
Coverify not working with babelify

### ISSUE THREAD

**Issue by mantoni** [substack/coverify#16]
I received [this bug report for Mochify](https://github.com/mantoni/mochify.js/issues/74) and tracked it down like this:

Put this script into `test.js`:

```js
import assert from "assert";

describe('Basic Test', () => {
  it("should understand ES6", () => {
    assert.equal(true, true);
  });
});
```

Then

```
$ npm install browserify coverify babelify mocha mocaccino
```

I then run this pipeline, which is working fine:

```
$ node_modules/.bin/browserify --bare --transform babelify --transform coverify \
--plugin [ mocaccino --node ] ./test.js | node
COVERAGE "/Users/max/projects/test/test.js" [[0,13],[68,82],[61,82],[85,99],[61,105],[54,106],[37,108],[37,108],[15,109],[140,157],[124,158],[124,158],[111,159],[246,270],[246,271],[228,275],[200,276],[200,277],[184,279],[161,280],[161,281]]
COVERED "/Users/max/projects/test/test.js" 0
COVERED "/Users/max/projects/test/test.js" 8
COVERED "/Users/max/projects/test/test.js" 7
COVERED "/Users/max/projects/test/test.js" 6
COVERED "/Users/max/projects/test/test.js" 12
COVERED "/Users/max/projects/test/test.js" 11
COVERED "/Users/max/projects/test/test.js" 10
COVERED "/Users/max/projects/test/test.js" 9
COVERED "/Users/max/projects/test/test.js" 5
COVERED "/Users/max/projects/test/test.js" 4
COVERED "/Users/max/projects/test/test.js" 2
COVERED "/Users/max/projects/test/test.js" 1
COVERED "/Users/max/projects/test/test.js" 20
COVERED "/Users/max/projects/test/test.js" 19
COVERED "/Users/max/projects/test/test.js" 18
COVERED "/Users/max/projects/test/test.js" 17
COVERED "/Users/max/projects/test/test.js" 16
COVERED "/Users/max/projects/test/test.js" 15
1..1
COVERED "/Users/max/projects/test/test.js" 14
COVERED "/Users/max/projects/test/test.js" 13
ok 1 Basic Test should understand ES6
# tests 1
# pass 1
# fail 0
```

But if I filter the output through coverify, it breaks:

```
$ node_modules/.bin/browserify --bare --transform babelify --transform coverify \
--plugin [ mocaccino --node ] ./test.js | node | node_modules/.bin/coverify
1..1
ok 1 Basic Test should understand ES6
# tests 1
# pass 1
# fail 0


/Users/max/projects/test/node_modules/coverify/bin/cmd.js:98
                        var rep = Array(b - a + 1).join('^');
                                  ^
RangeError: Invalid array length
    at /Users/max/projects/test/node_modules/coverify/bin/cmd.js:98:35
    at Array.forEach (native)
    at /Users/max/projects/test/node_modules/coverify/bin/cmd.js:75:29
    at Array.forEach (native)
    at /Users/max/projects/test/node_modules/coverify/bin/cmd.js:74:22
    at Array.forEach (native)
    at /Users/max/projects/test/node_modules/coverify/bin/cmd.js:66:32
    at Array.forEach (native)
    at /Users/max/projects/test/node_modules/coverify/bin/cmd.js:56:30
    at next (/Users/max/projects/test/node_modules/coverify/parse.js:110:17)
```

Any ideas?

**Comment by mantoni** [comment]
From looking at it, my guess is that for this to work, coverify would have to extract inline source maps and re-map to the original sources.

**Comment by pheuter** [comment]
It's been over a week, and almost a year since the last commit to master. I'm guessing coverify isn't under active development any longer?

**Comment by substack** [comment]
Should be good to go in 1.1.0! @chromakode just sent a great patch for this feature.
