### ISSUE TITLE
coverify doesn't work with babelify 7.x: file is not in the SourceMap

### ISSUE THREAD

**Issue by kuraga** [substack/coverify#23]
Error occurs with Babelify 7.0+ (Babel 6.x) and doesn't occur with Babelify 6.4 (Babel 5.x).

```
$ ./node_modules/.bin/browserify -t babelify -t coverify script.js 
```
```
/absolute/path/node_modules/coverify/node_modules/source-map/lib/source-map/source-map-consumer.js:697
        throw new Error('"' + aSource + '" is not in the SourceMap.');
              ^
Error: "/absolute/path/script.js" is not in the SourceMap.
    at SourceMapConsumer_sourceContentFor [as sourceContentFor] (node_modules/coverify/node_modules/source-map/lib/source-map/source-map-consumer.js:697:15)
    at DestroyableTransform.end [as _flush] (node_modules/coverify/index.js:44:38)
    at DestroyableTransform.<anonymous> (node_modules/coverify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at finishMaybe (node_modules/coverify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (node_modules/coverify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (node_modules/coverify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at Babelify.onend (_stream_readable.js:505:10)
    at Babelify.g (events.js:199:16)
```

**Comment by kuraga** [comment]
Related: https://github.com/babel/babelify/issues/174

**Comment by kuraga** [comment]
Solved in https://github.com/babel/babelify/commit/6997ff5bec307269978545e5295b46fc9f399f42
