### ISSUE TITLE
Error when using long format for --output CLI option

### ISSUE THREAD

**Issue by lzrski** [substack/coverify#24]
This works as expected:

```shell
browserifyinc \
  --cachefile build/browserify-cache.json \
  --transform coverify \
  --entry build/js/test.js \
  | tape-run \
  | coverify --color -o -
```

while this:

```shell
browserifyinc \
  --cachefile build/browserify-cache.json \
  --transform coverify \
  --entry build/js/test.js \
  | tape-run \
  | coverify --color --output -
```

results in following error:

```
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:540:11)
    at WriteStream.open (fs.js:1838:6)
    at new WriteStream (fs.js:1828:10)
    at Object.fs.createWriteStream (fs.js:1784:10)
    at Object.<anonymous> (/Users/tadeuszlazurski/Projects/basebuilder-ansible/data/application/cms/settings-editor/node_modules/coverify/bin/cmd.js:29:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

tadeuszlazurski@Tadeusz-Clansman:~/Projects/cms/settings-editor (upgrade/bb-1411-new-settings-integration)
```

Also Electron process executed by `tape-run` goes into a seemingly endless loop displaying window with this error message:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: channel closed
    at process.target.send (internal/child_process.js:523:16)
    at EventEmitter.<anonymous> (/Users/tadeuszlazurski/Projects/basebuilder-ansible/data/application/cms/settings-editor/node_modules/tape-run/node_modules/browser-run/node_modules/electron-stream/lib/runner.js:34:11)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/Users/tadeuszlazurski/Projects/basebuilder-ansible/data/application/cms/settings-editor/node_modules/tape-run/node_modules/browser-run/node_modules/electron-stream/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:130:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

and it has to be killed.

Seems like it might be caused by a bug in substack/minimist.

**Comment by tim-peterson** [comment]
May not be super useful but I'm observing a similar error when using a different Node package: gulper.

See my issue if you are curious: https://github.com/anatoo/gulper/issues/4
